<?php if (Auth::is_valid()): ?>
    <div class="pull-right">
        <?php echo Html::link("index/index","Crear Usuario","class='btn btn-default'") ?>
        <?php echo Html::link("index/logout","Cerrar Sesión","class='btn btn-danger'") ?>
    </div>
    <div class="clearfix"></div>
<?php endif ?>
<br>
<div class="row">
    <div class="col-md-4">
      <div class="panel panel-info" >
          <div class="panel-heading">
            <h3 class="panel-title">Nueva Carpeta</h3>
          </div>
          <div class="panel-body" style="height:300px;overflow:scroll">
            Panel content
          </div>
        </div>
        <div class="panel panel-info" >
          <div class="panel-heading">
            <h3 class="panel-title">Outbox</h3>
          </div>
          <div class="panel-body" style="height:300px;overflow:scroll">
            Panel content
          </div>
        </div>   
    </div>
    <div class="col-md-4">
       
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Candidatos</h3>
          </div>
          <div class="panel-body" >
            Panel content
          </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-info" >
          <div class="panel-heading">
            <h3 class="panel-title">Contactos</h3>
          </div>
          <div class="panel-body" id="contactos" style="height:300px;overflow:scroll">
            
          </div>
        </div>
        
        <?php View::partial("script_chat") ?>

        <div class="panel panel-info" >
            <div class="panel-heading">
            <h3 class="panel-title">Chat</h3>
          </div>
          <div class="panel-body" id="mensajes" style="height:250px;overflow:scroll">
          
          </div>
          <div class="panel-footer">
            <input type="text" class="form-control" id="texto" placeholder="Escribe aquí tu Mensaje">
          </div>
        </div>
    </div>
</div>