<?php if (Auth::is_valid()): ?>
    <div class="pull-right" >
        <?php echo Html::link("index/index","Crear Usuario","class='btn btn-default btn-xs'") ?>
        <?php echo Html::link("index/logout","Cerrar Sesión","class='btn btn-danger btn-xs'") ?>
    </div>
    <div class="clearfix"></div>
<?php endif ?>
<br>
<div class="row">
    <div class="col-md-4">
      <div class="panel panel-info" >
          <div class="panel-heading">
            <h3 class="panel-title">Carpetas</h3>
          </div>
          <div class="panel-body" style="height:290px;overflow:scroll">

            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <?php foreach ($carpetas as $key => $value): ?>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title">
                    <a role="button" style="text-decoration:none" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo str_replace(' ', '_',$value->nombre) ?>" aria-expanded="true" aria-controls="collapse<?php echo str_replace(' ', '_',$value->nombre) ?>">
                      <span class="glyphicon glyphicon-folder-open" class="carpetica_icono"></span> &nbsp;
                      <?php echo $value->nombre ?>
                    </a>
                  </h4>
                </div>
                <div id="collapse<?php echo str_replace(' ', '_',$value->nombre) ?>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                    <?php $paises = $obj_carpeta_data->getByCarpetaId($value->id) ?>
                    <?php foreach ($paises as $key2 => $value2): ?>
                      <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                          <h4 class="panel-title">
                            <a role="button" style="text-decoration:none" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo str_replace(' ', '-',$value2->id.date("Y_m_d_H:i:s")) ?>" aria-expanded="true" aria-controls="collapse<?php echo str_replace(' ', '-',$value2->id.date("Y_m_d_H:i:s")) ?>">
                              <span class="glyphicon glyphicon-folder-open" class="carpetica_icono"></span> &nbsp;
                              <?php echo $value2->Pais."-".$value2->estado ?>
                            </a>
                          </h4>
                        </div>
                        <div id="collapse<?php echo str_replace(' ', '-',$value2->id.date("Y_m_d_H:i:s")) ?>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                          <div class="panel-body">
                            
                          </div>
                        </div>
                      </div>
                    <?php endforeach ?>
                  </div>
                </div>
              </div>

            <?php endforeach ?>
              
           

            </div>

          </div>
        </div>
        <div class="panel panel-info" >
          <div class="panel-heading">
            <h3 class="panel-title">Outbox</h3>
          </div>
          <div class="panel-body" style="height:290px;overflow:scroll">
            Panel content
          </div>
        </div>   
    </div>
    <div class="col-md-4">
       
        <div class="panel panel-info">
          <div class="panel-heading">
            <div class="pull-left">
              <h3 class="panel-title">Candidatos</h3>
            </div>
            
            <div class="pull-right">
              
                
              <div class="dropdown">

                <button id="dLabel" type="button" class="btn btn-default btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Búsqueda
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dLabel">
                          <li style="padding:4px"><input type="text" id="filtrar_nombre" class="form-control input-sm input-busqueda" placeholder="Nombre" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_puesto" class="form-control input-sm input-busqueda" placeholder="Ultimo Puesto" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_edad" class="form-control input-sm input-busqueda" placeholder="Edad" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_pais" class="form-control input-sm input-busqueda" placeholder="Pais" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_estado" class="form-control input-sm input-busqueda" placeholder="Estado" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_descripcion" class="form-control input-sm input-busqueda" placeholder="Descripcion" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_idioma1" class="form-control input-sm input-busqueda" placeholder="Idioma 1" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_idioma2" class="form-control input-sm input-busqueda" placeholder="Idioma 2" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_idioma3" class="form-control input-sm input-busqueda" placeholder="Idioma 3" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_carrera" class="form-control input-sm input-busqueda" placeholder="Carrera" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_institucion" class="form-control input-sm input-busqueda" placeholder="Institucion" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_habilidades" class="form-control input-sm input-busqueda" placeholder="Habilidades" style="width:100%"></li>
                          <li style="padding:4px"><input type="text" id="filtrar_sueldo" class="form-control input-sm input-busqueda" placeholder="Sueldo" style="width:100%"></li>
                </ul>
              </div>
            </div>
              <div class="pull-right">
                <!--<button class="btn btn-default btn-xs" id="mostrar_todo">Mostrar Todo</button>-->
              </div>
            <div class="clearfix"></div>
          </div>
          <?php echo View::partial("script_filtrar_li") ?>
          <div class="panel-body" style="height:580px;overflow:scroll">
            <ul class="list-group" id="lista_candidatos">
            <?php $contador = 1; ?>
              <?php foreach ($data as $key => $value): ?>
                <li class="list-group-item"> 
                    <?php 
                      $info = "Nombre: ".ucfirst($value->Nombre)." ".ucfirst($value->Nombre_2)." ".ucfirst($value->Apellido_Paterno)." ".ucfirst($value->Apellido_Materno)." 
Nac: ".$value->dia_de_nacimiento."-".$value->mes_de_nacimiento."-19".$value->ano_de_nacimiento."
Edad: ".Util::calculaedad($value->dia_de_nacimiento."-".$value->mes_de_nacimiento."-19".$value->ano_de_nacimiento)." 
Direc: ".$value->Pais." ".$value->estado." ".$value->colonia." ".$value->calle." ".$value->numero." 
Ult.Puesto: ".$value->Ultimo_puesto." - ".$value->descripción."
Fec.Ingreso: ".$value->fecha_de_ingreso."
Fec.Salida: ".$value->fecha_de_salida."
Puesto 1: ".$value->Puesto_1." - ".$value->descripción_puesto_1."
Idiomas: ".$value->Idioma_1."(".$value->porcentaje_de_idioma_1."), ".$value->Idioma_2."(".$value->porcentaje_de_idioma_2."), ".$value->Idioma_3."(".$value->porcentaje_de_idioma_3.")"."
Carrera: ".$value->Carrera_o_profesion." ".$value->Institucion_o_universidad."(".$value->ano_de_ingreso_universidad."-".$value->ano_de_finalización_universidad.")
Cursos: ".$value->Curso_1.", ".$value->Curso_2.", ".$value->Curso_3."
Habilidades: ".$value->Habilidades."
Sueldo: ".$value->sueldo;
                     ?>
                    <div class="pull-right"><span class="badge" title="<?php echo $info ?>"> Ver Perfil</span></div>
                    <div class="clearfix"></div>
                    <?php echo $contador ?>
                    <?php $contador++ ?>
                    &nbsp;<input type="checkbox"  class="seleccionar_candidato" id="<?php echo $value->id ?>"> 
                    <span style="display:none"><?php echo $value->sexo ?></span>
                    <span style="display:none"><?php echo $info ?></span>
                    
                    <?php if (strtolower($value->sexo) == "hombre" ): ?>
                      <?php echo Html::img("hombre_icono.png","","width='30px'") ?>
                      <?php else: ?>
                      <?php echo Html::img("mujer_icono.png","","width='30px'") ?>
                    <?php endif ?>
                   
                    <span class="nombre" carrera="<?php echo $value->Ultimo_puesto ?>" pais-estado="<?php echo $value->Pais."-".$value->estado ?>"><?php echo ucfirst($value->Nombre)." ".ucfirst($value->Apellido_Paterno) ?> 

                    <span class="label label-default" class="carrera"><?php echo ucfirst($value->Ultimo_puesto) ?></span> <br>
                    &nbsp; &nbsp; &nbsp; &nbsp; <?php echo ucfirst($value->Pais)."-".ucfirst($value->estado) ?></span> &nbsp; 
                </li>
              <?php endforeach ?>
            </ul>
          </div>
          <div class="panel-footer">
            <div class="pull-left">
              <input type="button" id="crear_carpeta" class="btn btn-info" value="Enviar a Carpeta">
            </div>
            <div class="pull-right">
              <input type="button" id="enviar_a_contacto" class="btn btn-info" value="Enviar a Contacto">
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-info" >
          <div class="panel-heading">
            <h3 class="panel-title">Contactos</h3>
          </div>
          <div class="panel-body" id="contactos" style="height:280px;overflow:scroll">
            
          </div>
        </div>
        
        <?php View::partial("script_chat") ?>

        <div class="panel panel-info" >
            <div class="panel-heading">
            <h3 class="panel-title">Chat</h3>
          </div>
          <div class="panel-body" id="mensajes" style="height:250px;overflow:scroll">
          
          </div>
          <div class="panel-footer">
            <input type="text" class="form-control" id="texto" placeholder="Escribe aquí tu Mensaje, Luego presiona ENTER">
          </div>
        </div>
    </div>
</div>

<!-- MODAL PARA FILTROS -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Búsqueda</h4>
      </div>
      <div class="modal-body">
        <p>

        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<style type="text/css">
  input[type=checkbox]
  {
    /* Double-sized Checkboxes */
    -ms-transform: scale(2); /* IE */
    -moz-transform: scale(2); /* FF */
    -webkit-transform: scale(2); /* Safari and Chrome */
    -o-transform: scale(2); /* Opera */
    padding: 10px;
    margin-left: 5px;
    margin-right: 5px;
  }
</style>
<script type="text/javascript">
var candidatos_selecionados = [];
  $(document).ready(function(){


    $('.collapse').on('hidden.bs.collapse', function () {

      a = $("a[href='#"+$(this).attr("id")+"']").find("span");
      a.addClass("glyphicon-folder-close")
      a.removeClass("glyphicon-folder-open")
    })
    $('.collapse').on('show.bs.collapse', function () {
      
      a = $("a[href='#"+$(this).attr("id")+"']").find("span")
      a.removeClass("glyphicon-folder-close")
      a.addClass("glyphicon-folder-open")
    })

    $("body").on("click","#crear_carpeta",function(evt){
      var nombre_carpeta = prompt("Ingresa el nombre de la nueva carpeta!");
      $(".seleccionar_candidato:checked").each(function(){
        id = $(this).attr("id");
        li = $(this).parent();
 
        nombre = li.find(".nombre").text();
        carrera = li.find(".nombre").attr("carrera");
        pais_estado = li.find(".nombre").attr("pais-estado");

        candidatos_selecionados.push(new Candidato(id,nombre_carpeta,nombre,carrera,pais_estado));
      })
      $.ajax({
        url:"crear_carpeta",
        data:{carpeta:JSON.stringify(candidatos_selecionados)},
        type:"POST",
        async:false,
        dataType:"json",
        success:function(r){
          console.log(r)
          nombre_carpeta = "";
          candidatos_selecionados = [];
        }
      })
      
    })


    $("body").on("click","#enviar_a_contacto",function(evt){
      
    })


  });
function Candidato(id,nombre_carpeta, nombre,carrera,pais_estado){
  return {
    'id': id,
    'nombre_carpeta': nombre_carpeta,
    'nombre': nombre,
    'carrera': carrera,
    "pais_estado" : pais_estado
  };
}
</script>