<div class="row">
    <?php echo View::content(); ?>
    <?php if (Auth::is_valid()): ?>
            <div class="pull-right">
                <?php echo Html::link("index/dashboard","Ir a Dashboard","class='btn btn-default'") ?>
                <?php echo Html::link("index/logout","Cerrar Sesión","class='btn btn-danger'") ?>
            </div>
            <div class="clearfix"></div>
    <?php endif ?>
    <div class="col-md-4">
    <?php if (Auth::is_valid() and Auth::get("role_id") == 1): ?>
        
        <div class="page-header">
          <center>
              <h1><small>Registro de Usuarios</small></h1>
          </center>
        </div>
            <?php echo Form::open("index/registro"); ?>
            <div class="form-group">
                <?php echo Form::label("Usuario","login"); ?>
                <?php echo Form::text("login","class='form-control'"); ?>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo Form::label("Password","password"); ?>
                        <?php echo Form::pass("password","class='form-control'"); ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo Form::label("Repetir Password","Repetir Password"); ?>
                        <?php echo Form::pass("repeat_password","class='form-control'"); ?>
                    </div>
                </div>
            </div>
            <div class="pull-right">
                <input type="submit" value="Registrar" class="btn btn-success">
            </div>
            <div class="clearfix"></div>
            <?php echo Form::close(); ?>
    <?php endif ?>
    </div>
    <div class="col-md-4">
        <div class="page-header">
          <center>
              <h1><small>Sistema para intercambio de perfiles</small></h1>
          </center>
        </div>
            <?php echo Form::open("index/login"); ?>
            <div class="form-group">
                <?php echo Form::label("Usuario","login"); ?>
                <?php echo Form::text("login","class='form-control'"); ?>
            </div>
            <div class="form-group">
                <?php echo Form::label("Password","password"); ?>
                <?php echo Form::pass("password","class='form-control'"); ?>
            </div>
            
            <div class="pull-right">
                <input type="submit" value="Ingresar"  class="btn btn-success">
            </div>
            <div class="clearfix"></div>
            <?php echo Form::close(); ?>
    </div>
    <div class="col-md-4">
        <?php if (Auth::is_valid() and Auth::get("role_id") == 1): ?>
        <div class="page-header">
          <center>
              <h1><small>Lista de Usuarios</small></h1>
          </center>
        </div>
            <table class="table table-bordered table-striped">
                <thead>
                    <td>Id</td>
                    <td>Login</td>
                    <td>Creado</td>
                </thead>
                <?php foreach ($usuarios as $key => $value): ?>
                    <tr>
                        <td><?php echo $value->id ?></td>
                        <td><?php echo $value->login ?></td>
                        <td><?php echo $value->created ?></td>
                    </tr>
                <?php endforeach ?>
            </table>
        <?php endif; ?>
    </div>
</div>